sonar.projectKey=dand-21my_ProjetoFinal_To-Do
sonar.organization=dand-21my

# Fonte
sonar.sources=src
sonar.exclusions=**/*test*.js,node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*test.js

# Cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Análise
sonar.sourceEncoding=UTF-8
